# This file generates the GitHub Actions matrix.
# See https://zmk.dev/docs/customization for more information.
---
include:
  - board: nice_nano_v2
    shield: charbdis_hw_left
  - board: nice_nano_v2
    shield: charbdis_hw_right
